# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20151228_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choise',
            old_name='coice_text',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='choise',
            old_name='bote',
            new_name='vote',
        ),
    ]
