# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20151228_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choise',
            name='choice_text',
            field=models.CharField(max_length=200),
        ),
    ]
